name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install just
        uses: extractions/setup-just@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install tooling (justfile path)
        if: ${{ hashFiles('justfile') != '' }}
        run: |
          just init

      - name: Install tooling (fallback if no justfile)
        if: ${{ hashFiles('justfile') == '' }}
        run: |
          python -m pip install -U pip
          pip install black ruff mypy pytest

      - name: Run quality checks (justfile path)
        if: ${{ hashFiles('justfile') != '' }}
        run: |
          just all

      - name: Run quality checks (fallback if no justfile)
        if: ${{ hashFiles('justfile') == '' }}
        run: |
          black --check .
          ruff check .
          mypy .
          pytest -q